CREATE TABLE quran_juzs( id INTEGER PRIMARY KEY AUTO_INCREMENT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP(), updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP() , juz INTEGER, surah_id INTEGER, ayah_id INTEGER, FOREIGN kEY (surah_id) REFERENCES quran_surahs(id), FOREIGN kEY (ayah_id) REFERENCES quran_ayahs(id));
INSERT INTO quran_juzs (juz, ayah_id) SELECT 6 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 641 AND 750;
INSERT INTO quran_juzs (juz, surah_id) SELECT 6 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 641 AND 750 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 11 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1328 AND 1478;
INSERT INTO quran_juzs (juz, surah_id) SELECT 11 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1328 AND 1478 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 30 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 5673 AND 6236;
INSERT INTO quran_juzs (juz, surah_id) SELECT 30 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 5673 AND 6236 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 13 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1649 AND 1802;
INSERT INTO quran_juzs (juz, surah_id) SELECT 13 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1649 AND 1802 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 15 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 2030 AND 2214;
INSERT INTO quran_juzs (juz, surah_id) SELECT 15 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 2030 AND 2214 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 22 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 3564 AND 3732;
INSERT INTO quran_juzs (juz, surah_id) SELECT 22 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 3564 AND 3732 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 24 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 4090 AND 4264;
INSERT INTO quran_juzs (juz, surah_id) SELECT 24 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 4090 AND 4264 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 14 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1803 AND 2029;
INSERT INTO quran_juzs (juz, surah_id) SELECT 14 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1803 AND 2029 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 28 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 5105 AND 5241;
INSERT INTO quran_juzs (juz, surah_id) SELECT 28 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 5105 AND 5241 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 7 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 751 AND 899;
INSERT INTO quran_juzs (juz, surah_id) SELECT 7 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 751 AND 899 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 17 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 2484 AND 2673;
INSERT INTO quran_juzs (juz, surah_id) SELECT 17 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 2484 AND 2673 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 20 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 3215 AND 3385;
INSERT INTO quran_juzs (juz, surah_id) SELECT 20 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 3215 AND 3385 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 25 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 4265 AND 4510;
INSERT INTO quran_juzs (juz, surah_id) SELECT 25 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 4265 AND 4510 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 1 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1 AND 148;
INSERT INTO quran_juzs (juz, surah_id) SELECT 1 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1 AND 148 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 19 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 2876 AND 3214;
INSERT INTO quran_juzs (juz, surah_id) SELECT 19 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 2876 AND 3214 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 2 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 149 AND 259;
INSERT INTO quran_juzs (juz, surah_id) SELECT 2 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 149 AND 259 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 9 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1042 AND 1200;
INSERT INTO quran_juzs (juz, surah_id) SELECT 9 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1042 AND 1200 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 21 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 3386 AND 3563;
INSERT INTO quran_juzs (juz, surah_id) SELECT 21 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 3386 AND 3563 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 27 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 4706 AND 5104;
INSERT INTO quran_juzs (juz, surah_id) SELECT 27 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 4706 AND 5104 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 29 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 5242 AND 5672;
INSERT INTO quran_juzs (juz, surah_id) SELECT 29 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 5242 AND 5672 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 12 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1479 AND 1648;
INSERT INTO quran_juzs (juz, surah_id) SELECT 12 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1479 AND 1648 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 16 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 2215 AND 2483;
INSERT INTO quran_juzs (juz, surah_id) SELECT 16 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 2215 AND 2483 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 26 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 4511 AND 4705;
INSERT INTO quran_juzs (juz, surah_id) SELECT 26 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 4511 AND 4705 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 3 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 260 AND 385;
INSERT INTO quran_juzs (juz, surah_id) SELECT 3 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 260 AND 385 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 4 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 386 AND 516;
INSERT INTO quran_juzs (juz, surah_id) SELECT 4 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 386 AND 516 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 5 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 517 AND 640;
INSERT INTO quran_juzs (juz, surah_id) SELECT 5 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 517 AND 640 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 8 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 900 AND 1041;
INSERT INTO quran_juzs (juz, surah_id) SELECT 8 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 900 AND 1041 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 10 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 1201 AND 1327;
INSERT INTO quran_juzs (juz, surah_id) SELECT 10 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 1201 AND 1327 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 18 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 2674 AND 2875;
INSERT INTO quran_juzs (juz, surah_id) SELECT 18 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 2674 AND 2875 GROUP BY surah_id;
INSERT INTO quran_juzs (juz, ayah_id) SELECT 23 as juz, id as ayah_id FROM quran_ayahs WHERE id BETWEEN 3733 AND 4089;
INSERT INTO quran_juzs (juz, surah_id) SELECT 23 as juz, surah_id FROM quran_ayahs WHERE id BETWEEN 3733 AND 4089 GROUP BY surah_id;
